/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_de_scolarité.PL;

import gestion_de_scolarité.BL.Administrateur;
import gestion_de_scolarité.BL.Enseignant;
import gestion_de_scolarité.PL.AdminAccount.AdminDashboard;
import gestion_de_scolarité.PL.EnseignantAccount.EnseignantDashboard;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.beans.EventHandler;
import java.io.IOException;
import javafx.fxml.FXMLLoader;
import javafx.stage.Stage;
import javafx.stage.StageStyle;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author slimane
 */
public class LoginForm extends javax.swing.JFrame {
    
    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        comboUsers.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        theUser = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        comboUsers = new javax.swing.JPanel();
        directeur = new javax.swing.JLabel();
        admin = new javax.swing.JLabel();
        enseignant = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 400));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(39, 65, 238));

        jLabel2.setFont(new java.awt.Font("Abyssinica SIL", 0, 19)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Welcome to Ecolabs");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_de_scolarité/PL/icons_loginForm/ecolelogo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 0, 290, 400));

        jPanel3.setBackground(new java.awt.Color(254, 254, 254));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 340, -1));

        jSeparator2.setBackground(new java.awt.Color(206, 202, 198));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 240, 260, 14));

        theUser.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        theUser.setForeground(new java.awt.Color(78, 78, 78));
        theUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        theUser.setText("Choisis un");
        theUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                theUserMouseClicked(evt);
            }
        });
        jPanel1.add(theUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, 30));

        usernameField.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        usernameField.setForeground(new java.awt.Color(44, 44, 44));
        usernameField.setToolTipText("");
        usernameField.setBorder(null);
        usernameField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 240, 30));

        jSeparator1.setBackground(new java.awt.Color(206, 202, 198));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 170, 260, 14));

        jLabel3.setBackground(new java.awt.Color(39, 65, 238));
        jLabel3.setFont(new java.awt.Font("Kinnari", 1, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(122, 124, 138));
        jLabel3.setText("Login");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 100, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(139, 132, 132));
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 20, 30));

        passwordField.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        passwordField.setForeground(new java.awt.Color(44, 44, 44));
        passwordField.setBorder(null);
        passwordField.setPreferredSize(new java.awt.Dimension(73, 17));
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 240, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(150, 146, 146));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_de_scolarité/PL/icons_loginForm/smallarrow.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 20, 20));

        comboUsers.setBackground(new java.awt.Color(254, 254, 254));
        comboUsers.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        directeur.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        directeur.setForeground(new java.awt.Color(117, 110, 110));
        directeur.setText("Directeur");
        directeur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                directeurMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                directeurMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                directeurMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                directeurMouseEntered(evt);
            }
        });

        admin.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        admin.setForeground(new java.awt.Color(117, 110, 110));
        admin.setText("Admin");
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                adminMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminMouseEntered(evt);
            }
        });

        enseignant.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        enseignant.setForeground(new java.awt.Color(117, 110, 110));
        enseignant.setText("Enseignant");
        enseignant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enseignantMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enseignantMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enseignantMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enseignantMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout comboUsersLayout = new javax.swing.GroupLayout(comboUsers);
        comboUsers.setLayout(comboUsersLayout);
        comboUsersLayout.setHorizontalGroup(
            comboUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comboUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comboUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(directeur, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(admin, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(enseignant, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))
        );
        comboUsersLayout.setVerticalGroup(
            comboUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comboUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(directeur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(admin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enseignant)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(comboUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 120, 90));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_de_scolarité/PL/icons_loginForm/username.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 20, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_de_scolarité/PL/icons_loginForm/password.png"))); // NOI18N
        jLabel15.setText("jLabel13");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 20, 30));

        jButton1.setBackground(new java.awt.Color(39, 65, 238));
        jButton1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(254, 254, 254));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 80, 35));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(107, 107, 107));
        jLabel1.setText("password :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(107, 107, 107));
        jLabel6.setText("username :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        
        if(comboUsers.isVisible()){
            comboUsers.setVisible(false);
            jLabel5.setForeground(new Color(99,94,94));
        }else{
            comboUsers.setVisible(true);
            jLabel5.setForeground(new Color(150,146,146));
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void directeurMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_directeurMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_directeurMousePressed

    private void directeurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_directeurMouseClicked
        theUser.setText(directeur.getText().toString());
        comboUsers.setVisible(false);
    }//GEN-LAST:event_directeurMouseClicked

    private void directeurMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_directeurMouseExited
        directeur.setForeground(new Color(117,110,110));
        directeur.setFont(new Font(directeur.getName(), directeur.getFont().getStyle()-Font.BOLD, directeur.getFont().getSize()));
    }//GEN-LAST:event_directeurMouseExited

    private void directeurMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_directeurMouseEntered
        directeur.setForeground(new Color(38,34,34));
        directeur.setFont(new Font(directeur.getName(), Font.BOLD, directeur.getFont().getSize()));
    }//GEN-LAST:event_directeurMouseEntered

    private void adminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminMousePressed

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked
        theUser.setText(admin.getText().toString());
        comboUsers.setVisible(false);
    }//GEN-LAST:event_adminMouseClicked

    private void adminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseExited
        admin.setForeground(new Color(117,110,110));
        admin.setFont(new Font(admin.getName(), admin.getFont().getStyle()-Font.BOLD, admin.getFont().getSize()));
    }//GEN-LAST:event_adminMouseExited

    private void adminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseEntered
        admin.setForeground(new Color(38,34,34));
        admin.setFont(new Font(admin.getName(), Font.BOLD, admin.getFont().getSize()));
    }//GEN-LAST:event_adminMouseEntered

    private void enseignantMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enseignantMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_enseignantMousePressed

    private void enseignantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enseignantMouseClicked
        theUser.setText(enseignant.getText().toString());
        comboUsers.setVisible(false);
    }//GEN-LAST:event_enseignantMouseClicked

    private void enseignantMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enseignantMouseExited
        enseignant.setForeground(new Color(117,110,110));
        enseignant.setFont(new Font(enseignant.getName(), enseignant.getFont().getStyle()-Font.BOLD, enseignant.getFont().getSize()));
    }//GEN-LAST:event_enseignantMouseExited

    private void enseignantMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enseignantMouseEntered
        enseignant.setForeground(new Color(38,34,34));
        enseignant.setFont(new Font(enseignant.getName(), Font.BOLD, enseignant.getFont().getSize()));
    }//GEN-LAST:event_enseignantMouseEntered

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        if(comboUsers.isVisible()){
            comboUsers.setVisible(false);
            jLabel5.setForeground(new Color(99,94,94));
        }
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean access = false;
        LoginForm lf = new LoginForm();
     if(theUser.getText().equals(directeur.getText()) || theUser.getText().equals(admin.getText()) || theUser.getText().equals(enseignant.getText())){
        if(theUser.getText().equals(admin.getText())){
            Administrateur admin = new Administrateur();
            access = admin.login(usernameField.getText(), passwordField.getText());
            if(access == true){
                
                AdminDashboard ad = new AdminDashboard();
                ad.setVisible(true);
                lf.setVisible(false);
            }else{
                MessageDialog msg = new MessageDialog();
                msg.setVisible(true);
            }
        }else{
            if(theUser.getText().equals(enseignant.getText())){
             
             Enseignant ens = new Enseignant();
             access = ens.login(usernameField.getText(), passwordField.getText());
             if(access == true){
                 EnseignantDashboard  ensD= new EnseignantDashboard();
                 ensD.setVisible(true);
                 lf.setVisible(false);
                 
             }else{
                MessageDialog msg = new MessageDialog();
                msg.setVisible(true);
            }
            }
        }
     }else{
         MessageDialog msg = new MessageDialog();
         msg.messageText.setText("Choisissez un utilisateur!");
         msg.setVisible(true);
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void theUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_theUserMouseClicked
        if(comboUsers.isVisible()){
            comboUsers.setVisible(false);
            jLabel5.setForeground(new Color(99,94,94));
        }else{
            comboUsers.setVisible(true);
            jLabel5.setForeground(new Color(150,146,146));
        }
    }//GEN-LAST:event_theUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin;
    private javax.swing.JPanel comboUsers;
    private javax.swing.JLabel directeur;
    private javax.swing.JLabel enseignant;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel theUser;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
